### ISSUE TITLE
Review of 'Structured UV/Vis (meta)data for small molecule characterisation'

### ISSUE THREAD

**Issue by stuchalk** [IUPAC/WFChemCookbook#15]
*Which page are you reviewing?*
https://iupac.github.io/WFChemCookbook/samples/uvvis_metadata.html

*What is your ORCID*
https://orcid.org/0000-0002-0703-7776

*Review*
This recipe outlines metadata to be included in the reporting of UVVIS spectra and includes a Python script for processing of a spectrum and generation of characteristic metadata.  The recipe is comprehensive in its description and I like the organization of the different metadata levels that helps readers think about the different stages of the process. I particularly like the 'Doc string' text in the function which is both educational about Beer's law and also exemplifies best practice in documenting Python code.

Suggestions:
- Add citations to referenced papers/website and bibliography section at the end
- Add user information to the metadata table (new section ?) and dates/comments for timing of sample or spectrum collection
- Identify what 𝜆max is in the text and move the name of ε from the table to the text (Section 4). Use ε in the table instead of the name and add (see Section 4) in the table.  Not perfect that the symbols are used before being defined but more consistent.
- Section 5 might be better titled 'Glossary of Python Terms' and in the definition of 'method' I would add in brackets 'def in beer_lambert code above' (or something similar)

**Comment by S-Bloodworth** [comment]
Corrections have been made. 
All - please add any further comments. We'll close this issue in due course if there are no further suggestions.

**Comment by stuchalk** [comment]
Have the changes been pushed to GitHub?  I am not seeing a commit on this... (hopefully I am not blind...).

**Comment by Smund27** [comment]
All changes have been pushed now

**Comment by stuchalk** [comment]
Thanks, Sam. I pushed the changes this morning.
