### ISSUE TITLE
Link to cookbook in readme

### ISSUE THREAD

**Issue by nk1g09** [IUPAC/WFChemCookbook#16]
**Describe the bug**

Usage
See the [cookbook](https://iupac.github.io/WFChemCookbook/howtos_identifiers.html) for a user friendly, interactive portal for these resources.

(/howtos_identifiers.html )

I believe it should instead read as 

Usage
See the [cookbook](https://iupac.github.io/WFChemCookbook/index.html) for a user friendly, interactive portal for these resources.

(/index.html)

**Comment by stuchalk** [comment]
Thanks for pointing this out.  I will fix in the update I will do tomorrow morning...

**Comment by stuchalk** [comment]
Fixed in commit a5a0d51.
