### ISSUE TITLE
Review of IUPAC Gold Book API

### ISSUE THREAD

**Issue by vfscalfani** [IUPAC/WFChemCookbook#18]
*Which page are you reviewing?*
https://iupac.github.io/WFChemCookbook/samples/goldbook.html

*What is your ORCID*
http://orcid.org/0000-0002-7363-531X

*Review*

**General:**

Nice brief introduction to getting started with the IUPAC Gold Book API from @stuchalk 

**Suggested Revisions:**

1. Add a link to a general reference on regular expressions.
2. It would be useful to show a snippet of the API data with and without the `remove_html_tags` function to show why the function is helpful.
3. Typo: "Frab" should be "Grab"
4. Step 4 - it might be helpful for new users to emphasize that you are looping through a local dictionary of the saved API data, and not performing additional API calls.
5. Step 5 - Can you show the initial jsondata variable, and then the printed (indexed) definition? That will be helpful to understand what is being returned from the API, and why you are indexing into jsondata.

**Suggested Future Revisions (i.e., not necessary for version 1 of this recipe):**

1. Add a method in Steps 4 and 5 to show how to extract multiple terms into a list and then loop through the list to query the API for each definition.

**Comment by stuchalk** [comment]
Updated in commit e209cf6.  Let me know if there are any other changes.

**Comment by stuchalk** [comment]
Vin, any other changes?

**Comment by stuchalk** [comment]
Vin, can I close this issue?
