### ISSUE TITLE
make the Cookbook FAIR

### ISSUE THREAD

**Issue by egonw** [IUPAC/WFChemCookbook#20]
**Is your feature request related to a problem? Please describe.**
The Cookbook is not obviously meeting FAIR standards.

**Describe the solution you'd like**

* add a license information in the footer ("All rights reserved" is not a license)
* give the cookbook a global, unique identifier
* make clear who the authors of the book are

**Comment by egonw** [comment]
Okay, I now ran into the well hidden info for individual recipes:

![image](https://github.com/IUPAC/WFChemCookbook/assets/26721/3357fad0-4aa6-487b-8926-29070216c89d)

Please add a "license" link in the footer to explain where to find this info. 

And on the landing or main page info on who all the authors are and how to cite the book and/or how to cite an individual recipe would be welcome.

**Comment by stuchalk** [comment]
Egon, thanks for added this.  I will work on it later this week...

**Comment by stuchalk** [comment]
So the group has discussed licenses and unique identifiers (both for the overall site and individual recipes).  We have licenses in the infobox for recipes and will discuss wether or not to make more visible in the next couple of meetings. We did not add DOI's to the cookbook yet as we were only at a 'sample' (read 'trial') stage and new that links were likely to change.  We are going to add a DOI to the cookbook and likely to add them to individual recipes.  I will follow up as the project team discusses this topic...
