### ISSUE TITLE
possible bug in displau

### ISSUE THREAD

**Issue by egonw** [IUPAC/WFChemCookbook#21]
**Describe the bug**
I am not entirely sure, but the text in bold was likely meant as verbatim?

![image](https://github.com/IUPAC/WFChemCookbook/assets/26721/687be05b-202b-44f4-a0d9-0edd93f577f9)

**To Reproduce**
1. Go to https://iupac.github.io/WFChemCookbook/samples/goldbook.html
2. Scroll down to Step 2
4. Notice the text "I am surrounded by HTML tags" without visible HTML tags

**Expected behavior**
I am assuming it was supposed to look like `<b>I am surrounded by HTML tags</b>` or something similar with CSS and `<span></span>`

**Desktop (please complete the following information):**
 - Browser: Brave Version 1.51.114 Chromium: 113.0.5672.92 (Official Build) (64-bit)

**Comment by stuchalk** [comment]
OK, I have fixed the [presentation](https://github.com/IUPAC/WFChemCookbook/blob/main/book/samples/goldbook.ipynb) to make the example clearer.
