### ISSUE TITLE
Option to open Python notebooks in MyBinder and/or Google Colab

### ISSUE THREAD

**Issue by egonw** [IUPAC/WFChemCookbook#22]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a possible feature to make it easier for starting people: the open to open a recipe in MyBinder or Google Colab, for example with a button that opens a Jupyter notebook from the GitHub repo.

**Describe alternatives you've considered**
An alternative would be to just link to a matching Jupyter notebook in the GitHub repo.

**Comment by stuchalk** [comment]
Egon, great suggestion.  I will also work on this later this week...

**Comment by stuchalk** [comment]
I have added an example of this to the [OPSIN Jupyter Notebook](https://mybinder.org/v2/gh/IUPAC/WFChemCookbook/main?urlpath=tree/book/samples/opsin.ipynb).  Let me know what you think.

**Comment by stuchalk** [comment]
Can I close this, Egon?

**Comment by egonw** [comment]
Sorry, I missed this one, it seems. yes, looks great! MyBinder is giving me a 500 now, but that's on their side, as far as I can see. Thanks!
