### ISSUE TITLE
Incorrect contribution links in wiki / repo

### ISSUE THREAD

**Issue by nk1g09** [IUPAC/WFChemCookbook#40]
**Describe the bug**

Some links on wiki / repository are incorrect, most likely due to renaming of pages away from using IFCC abbreviation. Where the link is broken this instead goes directly to homepage of wiki. This issue highlights some places where links are incorrect but may not be all. 

- On wiki page https://github.com/IUPAC/WFChemCookbook/wiki/How-to-submit-a-contribution-to-the-Cookbook link to https://github.com/IUPAC/WFChemCookbook/wiki/Structure-and-Naming-of-IFCC-Contribution-Folders this is incorrect. Links should go to https://github.com/IUPAC/WFChemCookbook/wiki/Structure-and-Naming-of-Cookbook-Contribution-Folders
- The link is also incorrect in the github issue template https://github.com/IUPAC/WFChemCookbook/blob/62abd240ea5013fd7f3484e399bd4ce704bce4e1/.github/ISSUE_TEMPLATE/contribution.md?plain=1#L9
- Links to https://github.com/IUPAC/WFChemCookbook/wiki/IFCC-Contribution-Types on the issue template are also incorrect. 
- Links to https://github.com/IUPAC/WFChemCookbook/wiki/How-to-Submit-a-Contribution-to-the-IFCC#submit-a-pr-to-the-ifcc-github-repository on wiki page https://github.com/IUPAC/WFChemCookbook/wiki/How-to-create-content-for-the-Cookbook

Additionally content on the github repo (https://github.com/IUPAC/WFChemCookbook/blob/main/CONTRIBUTING.md) should probably reflect the new wiki and direct to there

**Comment by stuchalk** [comment]
Thanks Niki.  This is now resolved in commit [82f9858](https://github.com/IUPAC/WFChemCookbook/commit/82f9858435442d0d0891814d39de5730a37a4c24)
