### ISSUE TITLE
Add CAS Common Chem tutorial?

### ISSUE THREAD

**Issue by vfscalfani** [IUPAC/WFChemCookbook#5]
Here is a python tutorial for CAS Common Chem to consider adding. It's licensed as MIT, so we could reproduce a copy in the WFChemCookbook. thoughts? 

https://ualibweb.github.io/UALIB_ScholarlyAPI_Cookbook/content/scripts/python/python_casc.html

**Comment by vfscalfani** [comment]
I am submitting the PR now for this, let me know if I should make any changes. Thanks!

**Comment by stuchalk** [comment]
Thanks, Vin
