### ISSUE TITLE
Review of 'Computing InChIs'

### ISSUE THREAD

**Issue by stuchalk** [IUPAC/WFChemCookbook#6]
*Which page are you reviewing?*
https://iupac.github.io/WFChemCookbook/recipes/computing_inchis.html

*What is your ORCID*
https://orcid.org/0000-0002-0703-7776

*Review*
This review was done after I had already updated this Python notebook for the addition of more standardized descriptive metdata (see commit d07a33a).  I have split the review into two sections:  feedback that is generally useful across all the recipes, and feedback specific to this recipe.  I will also add some of these issues to the [discussions](https://github.com/IUPAC/WFChemCookbook/discussions) part of this repo.

General comments
- We should decide on an initial state for a Jupyuter notebook - show/hide 'outputs' of code blocks (see [discussion](https://github.com/IUPAC/WFChemCookbook/discussions/7))
- Headers should make clear statements about what the next block of code does
- If an identifier from a database is referenced a complete URL to the entry should be in the comments

Specific comments
- In the code block for 1.1 I don't see the need to print out the version of rdkit.  However, if it can be rework as a 'teachable moment' then it can remain with appropriate comments.
- In the first code block for 1.2, the second line 'm' needs an explanation (it looks like an error on its own)
- The code blocks for 1.3 need some explanation
- In the first line comment for code block 1.4 I suggest adding ' strings' at the end
- In the third and fifth code blocks for 1.4, same comment as for 1.2
- In the third block of 1.4 it might be good to show code that is a full for loop with initializing the moles variable and then in a comment show this succinct version of the for loop
- In the fourth block of 1.4 explain what 'SVG' means
- For 2.1, some comment to why two different modules are imported from Open Babel would be good
- In Binder, there is an error loading openbabel

**Comment by vfscalfani** [comment]
Thanks for the review! I have addressed and fixed all comments except the Binder openbabel issue. I'm not sure that is something I can fix? 

I will submit a PR in a few minutes with the updated notebook.
